/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { 
  FolderDown, 
  Download, 
  Upload, 
  Copy, 
  Check, 
  FileJson, 
  Trash2, 
  RefreshCw, 
  CheckCircle2, 
  AlertCircle, 
  X,
  HardDrive,
  Server,
  User,
  Clock,
  Layers,
  ArrowRight,
  ShieldCheck,
  Play
} from 'lucide-react';
import { Audiobook, LibraryMode, AudiobookshelfConfig } from '../types';
import { 
  downloadMapDataAsJson, 
  createMapDataPackage, 
  parseAndValidateMapJson, 
  SavedMapPackage,
  SavedMapFileSummary,
  saveMapToServer,
  fetchSavedMapsListFromServer,
  loadSavedMapFromServer,
  deleteSavedMapOnServer,
  getStandardSaveFilename
} from '../utils/storageUtils';
import { formatHours } from '../utils/colorUtils';

interface MapDataModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentBooks: Audiobook[];
  libraryPath: string;
  libraryMode: LibraryMode;
  absConfig?: AudiobookshelfConfig | null;
  lastSavedTimestamp?: string | null;
  onLoadMapData: (pkg: SavedMapPackage) => void;
  onResetToDefault: () => void;
}

export const MapDataModal: React.FC<MapDataModalProps> = ({
  isOpen,
  onClose,
  currentBooks,
  libraryPath,
  libraryMode,
  absConfig,
  lastSavedTimestamp,
  onLoadMapData,
  onResetToDefault
}) => {
  const [activeTab, setActiveTab] = useState<'appFolder' | 'export' | 'import'>('appFolder');
  const [serverFiles, setServerFiles] = useState<SavedMapFileSummary[]>([]);
  const [isLoadingFiles, setIsLoadingFiles] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccessMsg, setSaveSuccessMsg] = useState<string | null>(null);
  const [saveErrorMsg, setSaveErrorMsg] = useState<string | null>(null);
  const [loadingFilename, setLoadingFilename] = useState<string | null>(null);
  
  const [copiedJson, setCopiedJson] = useState(false);
  const [jsonPasteInput, setJsonPasteInput] = useState('');
  const [importStatus, setImportStatus] = useState<{ success?: boolean; message?: string; pkg?: SavedMapPackage } | null>(null);
  const [isDragging, setIsDragging] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Suggested filename based on ABS URL or Path
  const currentTargetName = absConfig?.serverUrl || libraryPath || 'audiobook-library';
  const autoGeneratedFilename = getStandardSaveFilename(currentTargetName);

  // Fetch saved maps from server folder
  const refreshSavedFiles = async () => {
    setIsLoadingFiles(true);
    try {
      const files = await fetchSavedMapsListFromServer();
      setServerFiles(files);
    } catch (err) {
      console.warn('Could not load saved maps list:', err);
    } finally {
      setIsLoadingFiles(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      refreshSavedFiles();
      setSaveSuccessMsg(null);
      setSaveErrorMsg(null);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const currentPkg = createMapDataPackage(libraryPath, currentBooks, libraryMode);
  const jsonString = JSON.stringify(currentPkg, null, 2);

  // Auto-Save to App Folder
  const handleSaveToAppFolder = async () => {
    setIsSaving(true);
    setSaveSuccessMsg(null);
    setSaveErrorMsg(null);

    const result = await saveMapToServer({
      nameOrPath: libraryPath,
      serverUrl: absConfig?.serverUrl || null,
      username: absConfig?.username || null,
      mode: libraryMode,
      audiobooks: currentBooks,
      totalDurationHours: currentPkg.totalDurationHours
    });

    setIsSaving(false);
    if (result.success && result.filename) {
      setSaveSuccessMsg(`Saved automatically to app folder as ${result.filename}`);
      refreshSavedFiles();
    } else {
      setSaveErrorMsg(result.error || 'Failed to save to app folder');
    }
  };

  // Load a specific file from server folder
  const handleLoadServerFile = async (filename: string) => {
    setLoadingFilename(filename);
    try {
      const pkg = await loadSavedMapFromServer(filename);
      if (pkg && pkg.audiobooks && pkg.audiobooks.length > 0) {
        onLoadMapData(pkg);
        onClose();
      } else {
        setSaveErrorMsg(`Could not parse audiobooks from ${filename}`);
      }
    } catch (err: any) {
      setSaveErrorMsg(err.message || `Failed to load ${filename}`);
    } finally {
      setLoadingFilename(null);
    }
  };

  // Delete a saved file
  const handleDeleteServerFile = async (filename: string) => {
    if (!confirm(`Are you sure you want to delete ${filename}?`)) return;
    const ok = await deleteSavedMapOnServer(filename);
    if (ok) {
      refreshSavedFiles();
    }
  };

  const handleCopyJson = () => {
    navigator.clipboard.writeText(jsonString);
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
  };

  const handleDownload = () => {
    downloadMapDataAsJson(libraryPath, currentBooks, libraryMode);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    readFile(file);
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) {
      readFile(file);
    }
  };

  const readFile = (file: File) => {
    const reader = new FileReader();
    reader.onload = (ev) => {
      const content = ev.target?.result as string;
      validateAndStageJson(content);
    };
    reader.onerror = () => {
      setImportStatus({ success: false, message: 'Failed to read the selected file.' });
    };
    reader.readAsText(file);
  };

  const validateAndStageJson = (text: string) => {
    const result = parseAndValidateMapJson(text);
    if (!result.valid || !result.data) {
      setImportStatus({
        success: false,
        message: result.error || 'Invalid JSON file format.'
      });
      return;
    }

    setImportStatus({
      success: true,
      message: `Valid map package detected with ${result.data.bookCount} audiobooks (${result.data.totalDurationHours} hrs).`,
      pkg: result.data
    });
  };

  const handleApplyImport = () => {
    if (importStatus?.pkg) {
      onLoadMapData(importStatus.pkg);
      onClose();
    }
  };

  return (
    <div 
      id="map-data-modal"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fadeIn"
      onClick={onClose}
    >
      <div 
        className="bg-[#12151A] border border-zinc-700/80 rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-800 bg-zinc-900/50">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-zinc-800 border border-zinc-700 flex items-center justify-center text-zinc-200">
              <FolderDown className="w-4 h-4 text-amber-200/90" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                <span>Save & Load Audiobook Maps</span>
              </h2>
              <p className="text-xs text-zinc-400">
                Persistent local storage formatted as <code className="text-zinc-300 font-mono text-[11px] bg-zinc-800 px-1 py-0.5 rounded">[server-url]-data.json</code>
              </p>
            </div>
          </div>
          <button 
            type="button"
            onClick={onClose}
            className="p-1.5 text-zinc-400 hover:text-white rounded-lg hover:bg-zinc-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b border-zinc-800 bg-zinc-950/40 px-6 pt-2 gap-2">
          <button
            type="button"
            onClick={() => { setActiveTab('appFolder'); setImportStatus(null); }}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-all cursor-pointer ${
              activeTab === 'appFolder'
                ? 'border-amber-200/90 text-white bg-zinc-800/40 rounded-t-lg'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <HardDrive className="w-3.5 h-3.5 text-amber-200/90" />
            <span>Saved Maps ({serverFiles.length})</span>
          </button>

          <button
            type="button"
            onClick={() => { setActiveTab('export'); setImportStatus(null); }}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-all cursor-pointer ${
              activeTab === 'export'
                ? 'border-amber-200/90 text-white bg-zinc-800/40 rounded-t-lg'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export File</span>
          </button>

          <button
            type="button"
            onClick={() => { setActiveTab('import'); setImportStatus(null); }}
            className={`flex items-center gap-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-all cursor-pointer ${
              activeTab === 'import'
                ? 'border-amber-200/90 text-white bg-zinc-800/40 rounded-t-lg'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <Upload className="w-3.5 h-3.5" />
            <span>Import JSON</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-5 flex-1 text-zinc-300 text-xs">
          
          {/* TAB 1: LOCAL APP FOLDER SAVE & SMART LOAD */}
          {activeTab === 'appFolder' && (
            <div className="space-y-4">
              
              {/* Quick Auto-Save Card */}
              <div className="p-4 bg-zinc-900/80 border border-zinc-800 rounded-xl space-y-3">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <span className="text-xs font-bold text-white flex items-center gap-1.5">
                      <HardDrive className="w-4 h-4 text-amber-200/90" />
                      <span>Auto-Save Current Library</span>
                    </span>
                    <p className="text-[11px] text-zinc-400">
                      Destination filename: <code className="font-mono text-zinc-200 bg-zinc-800 px-1.5 py-0.5 rounded border border-zinc-700">{autoGeneratedFilename}</code>
                    </p>
                  </div>
                  
                  <button
                    type="button"
                    onClick={handleSaveToAppFolder}
                    disabled={isSaving || currentBooks.length === 0}
                    className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-white font-semibold text-xs rounded-full border border-zinc-700 transition-all flex items-center gap-1.5 shadow-md cursor-pointer disabled:opacity-50"
                  >
                    {isSaving ? (
                      <>
                        <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                        <span>Saving...</span>
                      </>
                    ) : (
                      <>
                        <FolderDown className="w-3.5 h-3.5 text-amber-200/90" />
                        <span>Save to App Folder</span>
                      </>
                    )}
                  </button>
                </div>

                {saveSuccessMsg && (
                  <div className="p-2.5 bg-emerald-950/40 border border-emerald-800/60 rounded-lg text-emerald-300 text-xs flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 shrink-0 text-emerald-400" />
                    <span>{saveSuccessMsg}</span>
                  </div>
                )}

                {saveErrorMsg && (
                  <div className="p-2.5 bg-rose-950/40 border border-rose-800/60 rounded-lg text-rose-300 text-xs flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 shrink-0 text-rose-400" />
                    <span>{saveErrorMsg}</span>
                  </div>
                )}
              </div>

              {/* Saved Maps List / Selector */}
              <div className="space-y-2.5">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-bold text-white flex items-center gap-1.5">
                    <Server className="w-3.5 h-3.5 text-zinc-400" />
                    <span>Select Saved Server / User Map:</span>
                  </h3>
                  <button
                    type="button"
                    onClick={refreshSavedFiles}
                    className="text-[11px] text-zinc-400 hover:text-white flex items-center gap-1 transition-colors cursor-pointer"
                  >
                    <RefreshCw className={`w-3 h-3 ${isLoadingFiles ? 'animate-spin' : ''}`} />
                    <span>Refresh</span>
                  </button>
                </div>

                {isLoadingFiles ? (
                  <div className="p-8 text-center text-zinc-500 space-y-2">
                    <RefreshCw className="w-6 h-6 animate-spin mx-auto text-zinc-400" />
                    <p className="text-xs">Reading saved maps from app folder...</p>
                  </div>
                ) : serverFiles.length === 0 ? (
                  <div className="p-8 text-center bg-zinc-900/40 border border-zinc-800 rounded-xl space-y-2 text-zinc-400">
                    <HardDrive className="w-8 h-8 mx-auto text-zinc-600 mb-1" />
                    <p className="text-xs font-semibold text-zinc-300">No saved maps found in local app folder</p>
                    <p className="text-[11px] text-zinc-500">
                      Click &quot;Save to App Folder&quot; above or scan an audiobook collection to create your first saved map.
                    </p>
                  </div>
                ) : (
                  <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
                    {serverFiles.map((file) => {
                      const isTargetActive = file.nameOrPath === libraryPath;
                      const isLoadingThis = loadingFilename === file.filename;

                      return (
                        <div
                          key={file.filename}
                          className="p-3 bg-zinc-850 hover:bg-zinc-800/80 border border-zinc-800 hover:border-zinc-700 rounded-xl transition-all flex items-center justify-between gap-3 group"
                        >
                          <div className="min-w-0 space-y-1">
                            <div className="flex items-center gap-2">
                              <span className="font-semibold text-white text-xs truncate">
                                {file.nameOrPath}
                              </span>
                              {file.username && (
                                <span className="inline-flex items-center gap-1 text-[10px] bg-zinc-800 text-zinc-300 px-2 py-0.5 rounded-full border border-zinc-700">
                                  <User className="w-2.5 h-2.5" />
                                  <span>{file.username}</span>
                                </span>
                              )}
                              {file.mode === 'readList' && (
                                <span className="text-[10px] bg-amber-950/40 text-amber-300 border border-amber-800/50 px-1.5 py-0.5 rounded">
                                  My Shelf
                                </span>
                              )}
                            </div>

                            <div className="flex items-center gap-3 text-[11px] text-zinc-400">
                              <span className="font-mono text-zinc-300">
                                {file.bookCount} books
                              </span>
                              <span>•</span>
                              <span>{formatHours(file.totalDurationHours)}</span>
                              <span>•</span>
                              <span className="truncate font-mono text-[10px] text-zinc-500">
                                {file.filename}
                              </span>
                            </div>
                          </div>

                          <div className="flex items-center gap-2 shrink-0">
                            <button
                              type="button"
                              onClick={() => handleLoadServerFile(file.filename)}
                              disabled={isLoadingThis}
                              className="px-3.5 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-white font-medium text-xs rounded-full border border-zinc-700 transition-colors flex items-center gap-1.5 cursor-pointer shadow-xs"
                            >
                              {isLoadingThis ? (
                                <RefreshCw className="w-3 h-3 animate-spin" />
                              ) : (
                                <Play className="w-3 h-3 text-amber-200/90" />
                              )}
                              <span>Load</span>
                            </button>

                            <button
                              type="button"
                              onClick={() => handleDeleteServerFile(file.filename)}
                              className="p-1.5 text-zinc-500 hover:text-rose-400 hover:bg-rose-950/30 rounded-lg transition-colors cursor-pointer"
                              title="Delete saved map"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* TAB 2: EXPORT / DOWNLOAD */}
          {activeTab === 'export' && (
            <div className="space-y-4">
              <div className="p-4 bg-zinc-900/80 border border-zinc-800 rounded-xl space-y-3">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <span className="text-sm font-semibold text-white">Current Active Map</span>
                    <p className="text-[11px] text-zinc-400 font-mono truncate max-w-sm">
                      {libraryPath}
                    </p>
                  </div>
                  <div className="text-right">
                    <span className="text-base font-bold text-white">{currentBooks.length}</span>
                    <span className="text-[10px] text-zinc-400 block">audiobooks</span>
                  </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 pt-2 border-t border-zinc-800 text-[11px]">
                  <div>
                    <span className="text-zinc-500 block">Duration</span>
                    <span className="font-semibold text-zinc-200">{formatHours(currentPkg.totalDurationHours)}</span>
                  </div>
                  <div>
                    <span className="text-zinc-500 block">Mode</span>
                    <span className="font-semibold text-zinc-200">{libraryMode === 'readList' ? 'My Shelf' : 'Entire Library'}</span>
                  </div>
                  <div>
                    <span className="text-zinc-500 block">Format</span>
                    <span className="font-semibold text-zinc-300">JSON Package v1.0</span>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={handleDownload}
                  className="flex items-center justify-center gap-2 px-4 py-3 bg-zinc-800 hover:bg-zinc-700 text-white font-medium rounded-xl border border-zinc-700 shadow-md transition-all cursor-pointer"
                >
                  <Download className="w-4 h-4" />
                  <span>Download .JSON File</span>
                </button>

                <button
                  type="button"
                  onClick={handleCopyJson}
                  className="flex items-center justify-center gap-2 px-4 py-3 bg-zinc-800 hover:bg-zinc-750 text-zinc-200 font-medium rounded-xl border border-zinc-700 transition-all cursor-pointer"
                >
                  {copiedJson ? (
                    <>
                      <Check className="w-4 h-4 text-emerald-400" />
                      <span className="text-emerald-300">Copied to Clipboard!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      <span>Copy Raw JSON</span>
                    </>
                  )}
                </button>
              </div>

              {/* Collapsible JSON Preview */}
              <div className="space-y-1.5">
                <label className="text-[11px] font-semibold text-zinc-400">
                  JSON Raw Payload Preview
                </label>
                <div className="p-3 bg-zinc-950 border border-zinc-800 rounded-xl font-mono text-[10px] text-zinc-400 max-h-36 overflow-y-auto leading-relaxed select-all">
                  <pre>{jsonString.slice(0, 1500) + (jsonString.length > 1500 ? '\n... (truncated for preview)' : '')}</pre>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: IMPORT / UPLOAD */}
          {activeTab === 'import' && (
            <div className="space-y-4">
              {/* Drag and Drop Zone */}
              <div
                onDragOver={e => { e.preventDefault(); setIsDragging(true); }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={handleDrop}
                onClick={() => fileInputRef.current?.click()}
                className={`p-6 border-2 border-dashed rounded-xl flex flex-col items-center justify-center gap-2.5 transition-colors cursor-pointer text-center ${
                  isDragging 
                    ? 'border-amber-200 bg-zinc-800/40' 
                    : 'border-zinc-700 hover:border-zinc-500 bg-zinc-900/40'
                }`}
              >
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileSelect} 
                  accept=".json,application/json" 
                  className="hidden" 
                />
                <div className="w-10 h-10 rounded-full bg-zinc-800 flex items-center justify-center text-zinc-300">
                  <Upload className="w-5 h-5" />
                </div>
                <div>
                  <span className="font-semibold text-white block text-sm">
                    Drop your saved map JSON file here
                  </span>
                  <span className="text-[11px] text-zinc-400">
                    or click to browse from your computer
                  </span>
                </div>
              </div>

              {/* Paste JSON Option */}
              <div className="space-y-1.5">
                <label className="text-[11px] font-semibold text-zinc-400">
                  Or paste raw JSON content below:
                </label>
                <textarea
                  value={jsonPasteInput}
                  onChange={e => {
                    setJsonPasteInput(e.target.value);
                    if (e.target.value.trim()) {
                      validateAndStageJson(e.target.value);
                    } else {
                      setImportStatus(null);
                    }
                  }}
                  placeholder="Paste map package JSON text here..."
                  className="w-full h-24 p-3 bg-zinc-950 border border-zinc-800 rounded-xl font-mono text-[11px] text-zinc-300 focus:outline-none focus:border-zinc-600 resize-none"
                />
              </div>

              {/* Validation Feedback */}
              {importStatus && (
                <div className={`p-3.5 rounded-xl border flex items-start gap-2.5 text-xs ${
                  importStatus.success 
                    ? 'bg-emerald-950/30 border-emerald-500/40 text-emerald-200' 
                    : 'bg-red-950/30 border-red-500/40 text-red-200'
                }`}>
                  {importStatus.success ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  ) : (
                    <AlertCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
                  )}
                  <div className="space-y-1 flex-1">
                    <p className="font-medium">{importStatus.message}</p>
                    {importStatus.pkg && (
                      <div className="text-[11px] opacity-90 font-mono">
                        Path/Name: {importStatus.pkg.nameOrPath} • {importStatus.pkg.bookCount} books
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Load Button */}
              {importStatus?.success && (
                <button
                  type="button"
                  onClick={handleApplyImport}
                  className="w-full py-3 bg-zinc-800 hover:bg-zinc-700 text-white font-semibold rounded-xl border border-zinc-700 shadow-lg transition-all flex items-center justify-center gap-2 cursor-pointer"
                >
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Load and Render this Map</span>
                </button>
              )}
            </div>
          )}

        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-zinc-800 bg-zinc-900/60 flex items-center justify-between text-xs text-zinc-400">
          <span>Persistent App Storage</span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-full transition-colors border border-zinc-700 cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

